# Generated by Django 4.2.3 on 2023-07-31 13:25

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Phuong Bui", email="pb@email.com", document="22342342", phone="093456789").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
